// <auto-generated />
using System;
using System.Net;
using EventLy.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EventLy.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261001014011_AddGuestsAndInvitations")]
    partial class AddGuestsAndInvitations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EventLy.Api.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("entity_type");

                    b.Property<IPAddress>("IpAddress")
                        .HasColumnType("inet")
                        .HasColumnName("ip_address");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("user_agent");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_logs_entity_type_entity_id");

                    b.HasIndex("OrganizationId", "Timestamp")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_audit_logs_organization_id_timestamp");

                    b.HasIndex("UserId", "Timestamp")
                        .HasDatabaseName("ix_audit_logs_user_id_timestamp");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("EventLy.Api.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ActivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("category");

                    b.Property<string>("CoverImageKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("cover_image_key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid?>("PackageId")
                        .HasColumnType("uuid")
                        .HasColumnName("package_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("time_zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("venue");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("WhatsappTemplate")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("whatsapp_template");

                    b.HasKey("Id")
                        .HasName("pk_events");

                    b.HasIndex("PackageId")
                        .HasDatabaseName("ix_events_package_id");

                    b.HasIndex("OrganizationId", "Date")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_events_organization_id_date")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("events", null, t =>
                        {
                            t.HasCheckConstraint("ck_events_category", "category IN ('Wedding','Corporate','Birthday','Community','Other')");

                            t.HasCheckConstraint("ck_events_status", "status IN ('Draft','PendingPayment','Active','Completed','Cancelled')");
                        });
                });

            modelBuilder.Entity("EventLy.Api.Entities.EventSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<bool>("IsCheckInSession")
                        .HasColumnType("boolean")
                        .HasColumnName("is_check_in_session");

                    b.Property<string>("MapsUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("maps_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("venue");

                    b.HasKey("Id")
                        .HasName("pk_event_sessions");

                    b.HasIndex("EventId", "SortOrder")
                        .HasDatabaseName("ix_event_sessions_event_id_sort_order");

                    b.ToTable("event_sessions", null, t =>
                        {
                            t.HasCheckConstraint("ck_event_sessions_times", "ends_at > starts_at");
                        });
                });

            modelBuilder.Entity("EventLy.Api.Entities.EventStaffAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_event_staff_assignments");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_event_staff_assignments_user_id");

                    b.HasIndex("EventId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_event_staff_assignments_event_id_user_id");

                    b.ToTable("event_staff_assignments", (string)null);
                });

            modelBuilder.Entity("EventLy.Api.Entities.Guest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<int>("NumberOfPeople")
                        .HasColumnType("integer")
                        .HasColumnName("number_of_people");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("guest_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_guests");

                    b.HasIndex("EventId", "Name")
                        .HasDatabaseName("ix_guests_event_id_name")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("guests", null, t =>
                        {
                            t.HasCheckConstraint("ck_guests_people", "number_of_people BETWEEN 1 AND 50");

                            t.HasCheckConstraint("ck_guests_type", "guest_type IN ('Individual','Group')");
                        });
                });

            modelBuilder.Entity("EventLy.Api.Entities.GuestSession", b =>
                {
                    b.Property<Guid>("GuestId")
                        .HasColumnType("uuid")
                        .HasColumnName("guest_id");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("GuestId", "SessionId")
                        .HasName("pk_guest_sessions");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_guest_sessions_session_id");

                    b.ToTable("guest_sessions", (string)null);
                });

            modelBuilder.Entity("EventLy.Api.Entities.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(22)
                        .HasColumnType("character(22)")
                        .HasColumnName("code")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<Guid>("GuestId")
                        .HasColumnType("uuid")
                        .HasColumnName("guest_id");

                    b.Property<DateTimeOffset?>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_invitations");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_invitations_code");

                    b.HasIndex("GuestId")
                        .IsUnique()
                        .HasDatabaseName("ux_invitations_guest");

                    b.HasIndex("EventId", "Status")
                        .HasDatabaseName("ix_invitations_event_status");

                    b.ToTable("invitations", null, t =>
                        {
                            t.HasCheckConstraint("ck_invitations_status", "status IN ('Active','Revoked')");

                            t.HasCheckConstraint("ck_invitations_type", "type IN ('Individual','Group')");
                        });
                });

            modelBuilder.Entity("EventLy.Api.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(254)
                        .HasColumnType("citext")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("contact_phone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_organizations");

                    b.HasIndex("OwnerUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_organizations_owner_user_id");

                    b.ToTable("organizations", null, t =>
                        {
                            t.HasCheckConstraint("ck_organizations_status", "status IN ('Active','Suspended')");
                        });
                });

            modelBuilder.Entity("EventLy.Api.Entities.Package", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("price");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_packages");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_packages_code");

                    b.ToTable("packages", null, t =>
                        {
                            t.HasCheckConstraint("ck_packages_price", "price >= 0");
                        });
                });

            modelBuilder.Entity("EventLy.Api.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<string>("CheckoutUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("checkout_url");

                    b.Property<Guid?>("ConfirmedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("confirmed_by");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid")
                        .HasColumnName("package_id");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider_reference");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("ConfirmedBy")
                        .HasDatabaseName("ix_payments_confirmed_by");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("ux_payments_one_paid")
                        .HasFilter("status = 'Paid'");

                    b.HasIndex("PackageId")
                        .HasDatabaseName("ix_payments_package_id");

                    b.HasIndex("EventId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_payments_event_id_created_at");

                    b.HasIndex("OrganizationId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_payments_organization_id_created_at");

                    b.HasIndex("Provider", "ProviderReference")
                        .IsUnique()
                        .HasDatabaseName("ux_payments_provider_ref");

                    b.HasIndex("Status", "ExpiresAt")
                        .HasDatabaseName("ix_payments_pending")
                        .HasFilter("status = 'Pending'");

                    b.ToTable("payments", null, t =>
                        {
                            t.HasCheckConstraint("ck_payments_amount", "amount >= 0");

                            t.HasCheckConstraint("ck_payments_provider", "provider IN ('Fake','Xendit','Manual')");

                            t.HasCheckConstraint("ck_payments_status", "status IN ('Pending','Paid','Failed','Expired','Cancelled')");
                        });
                });

            modelBuilder.Entity("EventLy.Api.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<Guid?>("ReplacedById")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid>("SecurityStamp")
                        .HasColumnType("uuid")
                        .HasColumnName("security_stamp");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_refresh_tokens_family_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("EventLy.Api.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<string>("GoogleSubject")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("google_subject");

                    b.Property<DateTimeOffset?>("LastSignInAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sign_in_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<Guid>("SecurityStamp")
                        .HasColumnType("uuid")
                        .HasColumnName("security_stamp");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("TermsAcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("terms_accepted_at");

                    b.Property<string>("TermsVersion")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("terms_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("GoogleSubject")
                        .IsUnique()
                        .HasDatabaseName("ix_users_google_subject")
                        .HasFilter("google_subject IS NOT NULL");

                    b.HasIndex("OrganizationId", "Role")
                        .HasDatabaseName("ix_users_organization_id_role");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_role", "role IN ('Root','Owner','Admin','Staff')");

                            t.HasCheckConstraint("ck_users_status", "status IN ('Invited','Active','Disabled')");
                        });
                });

            modelBuilder.Entity("EventLy.Api.Entities.Event", b =>
                {
                    b.HasOne("EventLy.Api.Entities.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_events_organizations_organization_id");

                    b.HasOne("EventLy.Api.Entities.Package", null)
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_events_packages_package_id");

                    b.OwnsOne("EventLy.Api.Entities.PackageSnapshot", "PackageSnapshot", b1 =>
                        {
                            b1.Property<Guid>("EventId");

                            b1.Property<string>("Code")
                                .IsRequired();

                            b1.Property<string>("Currency")
                                .IsRequired();

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.Property<Guid>("PackageId");

                            b1.Property<decimal>("Price");

                            b1.HasKey("EventId")
                                .HasName("pk_events");

                            b1.ToTable("events");

                            b1
                                .ToJson("package_snapshot")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("EventId")
                                .HasConstraintName("fk_events_events_event_id");

                            b1.OwnsOne("EventLy.Api.Entities.PackageFeatures", "Features", b2 =>
                                {
                                    b2.Property<Guid>("PackageSnapshotEventId");

                                    b2.Property<bool>("BackgroundMusicEnabled");

                                    b2.Property<bool>("CountdownEnabled");

                                    b2.Property<bool>("DigitalGiftEnabled");

                                    b2.Property<bool>("ExcelExport");

                                    b2.Property<int>("GalleryRetentionDays");

                                    b2.Property<bool>("GuestUploadEnabled");

                                    b2.Property<int>("MaxAdmins");

                                    b2.Property<int>("MaxGuestPhotosPerInvitation");

                                    b2.Property<int>("MaxGuests");

                                    b2.Property<int>("MaxPhotos");

                                    b2.Property<int>("MaxStaff");

                                    b2.Property<bool>("WishesEnabled");

                                    b2.Property<bool>("ZipDownload");

                                    b2.HasKey("PackageSnapshotEventId")
                                        .HasName("pk_events");

                                    b2.ToTable("events");

                                    b2.WithOwner()
                                        .HasForeignKey("PackageSnapshotEventId")
                                        .HasConstraintName("fk_events_events_package_snapshot_event_id");
                                });

                            b1.Navigation("Features")
                                .IsRequired();
                        });

                    b.Navigation("PackageSnapshot");
                });

            modelBuilder.Entity("EventLy.Api.Entities.EventSession", b =>
                {
                    b.HasOne("EventLy.Api.Entities.Event", null)
                        .WithMany("Sessions")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_event_sessions_events_event_id");
                });

            modelBuilder.Entity("EventLy.Api.Entities.EventStaffAssignment", b =>
                {
                    b.HasOne("EventLy.Api.Entities.Event", null)
                        .WithMany("StaffAssignments")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_event_staff_assignments_events_event_id");

                    b.HasOne("EventLy.Api.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_event_staff_assignments_users_user_id");
                });

            modelBuilder.Entity("EventLy.Api.Entities.Guest", b =>
                {
                    b.HasOne("EventLy.Api.Entities.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_guests_events_event_id");
                });

            modelBuilder.Entity("EventLy.Api.Entities.GuestSession", b =>
                {
                    b.HasOne("EventLy.Api.Entities.Guest", null)
                        .WithMany("Sessions")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_guest_sessions_guests_guest_id");

                    b.HasOne("EventLy.Api.Entities.EventSession", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_guest_sessions_event_sessions_session_id");
                });

            modelBuilder.Entity("EventLy.Api.Entities.Invitation", b =>
                {
                    b.HasOne("EventLy.Api.Entities.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invitations_events_event_id");

                    b.HasOne("EventLy.Api.Entities.Guest", null)
                        .WithOne("Invitation")
                        .HasForeignKey("EventLy.Api.Entities.Invitation", "GuestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invitations_guests_guest_id");
                });

            modelBuilder.Entity("EventLy.Api.Entities.Organization", b =>
                {
                    b.HasOne("EventLy.Api.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_organizations_users_owner_user_id");
                });

            modelBuilder.Entity("EventLy.Api.Entities.Package", b =>
                {
                    b.OwnsOne("EventLy.Api.Entities.PackageFeatures", "Features", b1 =>
                        {
                            b1.Property<Guid>("PackageId");

                            b1.Property<bool>("BackgroundMusicEnabled");

                            b1.Property<bool>("CountdownEnabled");

                            b1.Property<bool>("DigitalGiftEnabled");

                            b1.Property<bool>("ExcelExport");

                            b1.Property<int>("GalleryRetentionDays");

                            b1.Property<bool>("GuestUploadEnabled");

                            b1.Property<int>("MaxAdmins");

                            b1.Property<int>("MaxGuestPhotosPerInvitation");

                            b1.Property<int>("MaxGuests");

                            b1.Property<int>("MaxPhotos");

                            b1.Property<int>("MaxStaff");

                            b1.Property<bool>("WishesEnabled");

                            b1.Property<bool>("ZipDownload");

                            b1.HasKey("PackageId");

                            b1.ToTable("packages");

                            b1
                                .ToJson("feature")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("PackageId")
                                .HasConstraintName("fk_packages_packages_id");
                        });

                    b.Navigation("Features")
                        .IsRequired();
                });

            modelBuilder.Entity("EventLy.Api.Entities.Payment", b =>
                {
                    b.HasOne("EventLy.Api.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ConfirmedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_payments_users_confirmed_by");

                    b.HasOne("EventLy.Api.Entities.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payments_events_event_id");

                    b.HasOne("EventLy.Api.Entities.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payments_organizations_organization_id");

                    b.HasOne("EventLy.Api.Entities.Package", null)
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payments_packages_package_id");

                    b.OwnsOne("EventLy.Api.Entities.PackageSnapshot", "PackageSnapshot", b1 =>
                        {
                            b1.Property<Guid>("PaymentId");

                            b1.Property<string>("Code")
                                .IsRequired();

                            b1.Property<string>("Currency")
                                .IsRequired();

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.Property<Guid>("PackageId");

                            b1.Property<decimal>("Price");

                            b1.HasKey("PaymentId");

                            b1.ToTable("payments");

                            b1
                                .ToJson("package_snapshot")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("PaymentId")
                                .HasConstraintName("fk_payments_payments_id");

                            b1.OwnsOne("EventLy.Api.Entities.PackageFeatures", "Features", b2 =>
                                {
                                    b2.Property<Guid>("PackageSnapshotPaymentId");

                                    b2.Property<bool>("BackgroundMusicEnabled");

                                    b2.Property<bool>("CountdownEnabled");

                                    b2.Property<bool>("DigitalGiftEnabled");

                                    b2.Property<bool>("ExcelExport");

                                    b2.Property<int>("GalleryRetentionDays");

                                    b2.Property<bool>("GuestUploadEnabled");

                                    b2.Property<int>("MaxAdmins");

                                    b2.Property<int>("MaxGuestPhotosPerInvitation");

                                    b2.Property<int>("MaxGuests");

                                    b2.Property<int>("MaxPhotos");

                                    b2.Property<int>("MaxStaff");

                                    b2.Property<bool>("WishesEnabled");

                                    b2.Property<bool>("ZipDownload");

                                    b2.HasKey("PackageSnapshotPaymentId")
                                        .HasName("pk_payments");

                                    b2.ToTable("payments");

                                    b2.WithOwner()
                                        .HasForeignKey("PackageSnapshotPaymentId")
                                        .HasConstraintName("fk_payments_payments_package_snapshot_payment_id");
                                });

                            b1.Navigation("Features")
                                .IsRequired();
                        });

                    b.Navigation("PackageSnapshot")
                        .IsRequired();
                });

            modelBuilder.Entity("EventLy.Api.Entities.RefreshToken", b =>
                {
                    b.HasOne("EventLy.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EventLy.Api.Entities.User", b =>
                {
                    b.HasOne("EventLy.Api.Entities.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_users_organizations_organization_id");
                });

            modelBuilder.Entity("EventLy.Api.Entities.Event", b =>
                {
                    b.Navigation("Sessions");

                    b.Navigation("StaffAssignments");
                });

            modelBuilder.Entity("EventLy.Api.Entities.Guest", b =>
                {
                    b.Navigation("Invitation");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
